# Generated by Django 4.0.5 on 2022-06-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_billing_info_credit_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_info',
            name='credit_num',
            field=models.IntegerField(),
        ),
    ]
