# Generated by Django 4.0.5 on 2022-06-15 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_billing_info_credit_num'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
