# Generated by Django 4.0.5 on 2022-06-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_services_service_rename_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_type',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='credit_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='cvc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='expiration',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Billing_info',
        ),
    ]
