# Generated by Django 4.0.5 on 2022-06-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_user_card_type_user_credit_num_user_cvc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_type',
            field=models.CharField(blank=True, default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_num',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='cvc',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='expiration',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
