# Generated by Django 4.0.5 on 2022-07-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_user_card_type_alter_user_credit_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='birthday_day',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='service',
            name='birthday_month',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='service',
            name='birthday_year',
            field=models.IntegerField(blank=True, default=2000),
        ),
        migrations.AddField(
            model_name='service',
            name='first_name',
            field=models.CharField(blank=True, default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='gender',
            field=models.CharField(blank=True, default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='last_name',
            field=models.CharField(blank=True, default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='zipcode',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
