# Generated by Django 4.0.5 on 2022-07-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_service_birthday_day_service_birthday_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='birthday_month',
            field=models.CharField(blank=True, default='January', max_length=200),
        ),
    ]
